Change area icon
GrigoryKharchenko/Cinema pull request #12
Opened 2023-02-02 09:23 UTC by GrigoryKharchenko

Изменил область нажатия иконки для просмотра всех фильмов

2023-02-02 09:25 UTC, LuchemeteOtake requested changes

2023-02-02 09:25 UTC, LuchemeteOtake commented on app/src/main/res/layout/item_all_category.xml
> +            android:gravity="center"
а почему бы весь этот лейаут на констрейнт не переделать?

2023-02-02 11:34 UTC, LuchemeteOtake approved these changes

2023-02-03 04:19 UTC, Skripchenko-Nikolai approved these changes

2023-02-03 06:23 UTC, merged