Add staff screen
GrigoryKharchenko/Cinema pull request #26
Opened 2023-03-13 12:00 UTC by GrigoryKharchenko

Добавил экран со всем персоналом

2023-03-14 14:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            actorAdapter.submitList(actor?.take(MAX_ACTOR))
?.take(MAX_ACTOR) - вынести в момент до мапинга

2023-03-14 14:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            staffAdapter.submitList(staff?.take(MAX_STAFF))
аналогично

2023-03-14 14:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffViewModel.kt
> +            }.onSuccess {
дай название it

2023-03-14 14:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/TypeTitleStaff.kt
> +    data class FilmMakers(
FilmMakers и Actors одно и тоже - зачем это надо?

2023-03-14 14:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/adapter/StaffAdapter.kt
> +            tvNameStaff.text = staffModel.name ?: itemView.context.getString(R.string.unknown)
Проверка на null вынести в маппер

2023-03-14 15:58 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/TypeTitleStaff.kt
> +    data class FilmMakers(
Так как у них должны быть разные заголовки в зависимости, от того какая категория выбрана

2023-03-14 19:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffViewModel.kt
> +            }.onSuccess {
исправил

2023-03-14 19:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/adapter/StaffAdapter.kt
> +            tvNameStaff.text = staffModel.name ?: itemView.context.getString(R.string.unknown)
исправил

2023-03-14 19:59 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            actorAdapter.submitList(actor?.take(MAX_ACTOR))
исправил

2023-03-14 20:00 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            staffAdapter.submitList(staff?.take(MAX_STAFF))
исправил

2023-03-14 22:00 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmDetailMapper.kt
> +        character = character ?: "Неизвестно",
в ресурсы

2023-03-14 22:01 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/repository/StaffRepositoryImpl.kt
> +        return if (typeTitleStaff.titleStaff == context.getString(R.string.film_detail_film_worked)) {
это чего за сравнение со строкой из ресурсов?

2023-03-14 22:06 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +                        filmId = argument
а можно argument на что-то более осмысленное поменять?

2023-03-14 22:06 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +                    typeTitleStaff = TypeTitleStaff(
может создание TypeTitleStaff внутрь метода запихнуть, или отдельно сделать?

2023-03-14 22:08 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/model/StaffModel.kt
> +    val name: String,
а что изменилось что нулабельность пропала?

2023-03-14 22:09 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffFragment.kt
> +    private val argument: TypeTitleStaff by lazy {
название нормальное, пожалуйста

2023-03-14 22:13 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_staff.xml
> +        android:layout_width="match_parent"
0dp, либо кнстрейнты убирай, если мачпарент ставишь, они один хер не работают

2023-03-14 22:14 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_staff.xml
> +            android:layout_height="match_parent"
почему не wrap_content?

2023-03-15 08:18 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/model/StaffModel.kt
> +    val name: String,
обсудили

2023-03-15 08:18 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_staff.xml
> +        android:layout_width="match_parent"
исправил

2023-03-15 08:19 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_staff.xml
> +            android:layout_height="match_parent"
исправил

2023-03-15 08:19 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffFragment.kt
> +    private val argument: TypeTitleStaff by lazy {
исправил

2023-03-15 09:47 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/repository/StaffRepositoryImpl.kt
> +        return if (typeTitleStaff.titleStaff == context.getString(R.string.film_detail_film_worked)) {
Это случайно вообще залил, все поправил

2023-03-15 09:47 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +                    typeTitleStaff = TypeTitleStaff(
Исправил

2023-03-15 09:47 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/TypeTitleStaff.kt
> +    data class FilmMakers(
Исправил

2023-03-15 10:18 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/repository/StaffRepositoryImpl.kt
> +    override suspend fun getStuff(typeTitleStaff: TypeTitleStaff): List<StaffModel> {
а вообще этот метод делает не то что от него ожидаешь, и в параметр принимает не то что ожидаешь.
может лучше как-то по-другому сделать?

2023-03-16 09:46 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            tvCountGallery.text = filmDetailUiState.filmDetailUiModel.sizeGallery
вынеси в group

2023-03-16 09:46 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +    private fun openStaff(typeTitleStaff: TypeTitleStaff) {
вынеси отсюда, ниже аналогично

2023-03-16 09:46 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
>      private fun getStaff() {
функция боьше 60 строк, измени

2023-03-16 09:46 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffFragment.kt
> +    private fun initViewModel() {
вроде ты не инициализируешь viewModel, а делаешь другое

2023-03-16 09:46 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffViewModel.kt
> +    private fun getStaff() {
А если ошибка? Никак нельзя попытаться заново загрузить?

2023-03-16 13:13 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffViewModel.kt
> +    private fun getStaff() {
обработал

2023-03-16 13:13 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/repository/StaffRepositoryImpl.kt
> +    override suspend fun getStuff(typeTitleStaff: TypeTitleStaff): List<StaffModel> {
Исправил

2023-03-18 18:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            tvCountGallery.text = filmDetailUiState.filmDetailUiModel.sizeGallery
Исправил

2023-03-18 18:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +    private fun openStaff(typeTitleStaff: TypeTitleStaff) {
Исправил

2023-03-18 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
>      private fun getStaff() {
ты не туда посмотрел

2023-03-18 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffFragment.kt
> +    private fun initViewModel() {
исправил

2023-03-18 18:56 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            groupActor.isVisible = filmDetailUiState.filmDetailUiModel.isVisibleActors
filmDetailUiState.filmDetailUiModel - нельзя в with вынести?

2023-03-18 18:56 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
>                      _uiStateFlow.update { uiState ->
почему тут update?

2023-03-18 18:56 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffFragment.kt
> +                    tvError.isVisible = true
может стоит group создать в xml?

2023-03-18 18:56 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffViewModel.kt
> +    fun getStaff() {
почему не private

2023-03-18 19:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffViewModel.kt
> +    fun getStaff() {
потому что функция вызывается во фрагменте

2023-03-18 19:36 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            groupActor.isVisible = filmDetailUiState.filmDetailUiModel.isVisibleActors
Исправил

2023-03-18 19:54 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/staff/StaffFragment.kt
> +                    tvError.isVisible = true
Я сделал, но выглядеть лучше, оно от этого не стало

2023-03-18 20:00 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
>                      _uiStateFlow.update { uiState ->
Так как у нас UiState хранит в себе всего одно состояние, а по умолчанию у нас заданы значения и если мы будем эмитить значения, а не обновлять то нужно их все свойства записывать заново

2023-03-21 18:07 UTC, Skripi requested changes

2023-03-21 18:07 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            binding.flProgress.isVisible = isVisibleProgress
with

2023-03-21 18:08 UTC, Skripi approved these changes

2023-03-22 07:10 UTC, merged