Add section viewed
GrigoryKharchenko/Cinema pull request #27
Opened 2023-03-13 14:38 UTC by GrigoryKharchenko

2023-03-14 14:13 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    suspend fun deleteALlFilm()
deleteAll

2023-03-14 14:13 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    suspend fun insertFilm(filmViewedEntity: FilmViewedEntity)
insertOrUpdate

2023-03-14 14:13 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/domain/repository/DetailFilmRepository.kt
> +    suspend fun getFimEntity(id:Int): Result<FilmViewedEntity>
Почему тут стоит префикс Entity, а выше не стоит? И название не говорит о том, что возвращаешь

2023-03-14 14:13 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    fun subscribeToReceive(): Flow<List<FilmViewedEntity>>
Хочу понять. Ты просто копи паст сделал этого метода subscribeToReceive? Или ты предвидел, что он будет необходим? Если предвидел, то напиши мне, что именно ты предвидел)

2023-03-14 14:13 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +    private fun getEntity() {
Этот метод вообще для чего? Вообще не понял

2023-03-14 14:13 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/profilepage/ProfileViewModel.kt
> +        viewModelScope.launch(ioDispatcher) {
Зачем это viewModelScope.launch(ioDispatcher)?

2023-03-14 14:13 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/profilepage/ProfileViewModel.kt
> +        viewModelScope.launch(ioDispatcher) {
.launchIn(viewModelScope) - ты же это уже добавил

2023-03-14 14:25 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    fun subscribeToReceive(): Flow<List<FilmViewedEntity>>
Ну нам же необходимо получать данные из бд, чтобы их отображать на ui, а с помощью этого метода мы будем получать наши данные

2023-03-14 15:41 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    suspend fun deleteALlFilm()
Исправил

2023-03-14 15:41 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    suspend fun insertFilm(filmViewedEntity: FilmViewedEntity)
Исправил

2023-03-14 15:42 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/domain/repository/DetailFilmRepository.kt
> +    suspend fun getFimEntity(id:Int): Result<FilmViewedEntity>
Исправил

2023-03-14 15:42 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    fun subscribeToReceive(): Flow<List<FilmViewedEntity>>
Обсудили

2023-03-14 15:42 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/profilepage/ProfileViewModel.kt
> +        viewModelScope.launch(ioDispatcher) {
Исправил

2023-03-14 22:29 UTC, LuchemeteOtake requested changes

2023-03-14 22:29 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    suspend fun deleteALl()
чет вроде исправлял, да недоисправлял

2023-03-14 22:29 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmViewedMapper.kt
> +        genre = genre ?: "Неизвестно",
в ресурсы

2023-03-14 22:29 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/profilepage/adapter/ProfileAdapter.kt
> +            else ->
а давай тут сделаем так же как в создании холдера
is TypeCardCategoryUiModel.FilmUiModel
is TypeCardCategoryUiModel.FooterUiModel
else throw

2023-03-15 09:51 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/dao/FilmViewedDao.kt
> +    suspend fun deleteALl()
Теперь точно исправил

2023-03-15 09:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmViewedMapper.kt
> +        genre = genre ?: "Неизвестно",
Исправил

2023-03-15 09:58 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/profilepage/adapter/ProfileAdapter.kt
> +            else ->
Исправил

2023-03-18 18:59 UTC, merged