Add serial season screen
GrigoryKharchenko/Cinema pull request #30
Opened 2023-04-08 17:21 UTC by GrigoryKharchenko

Добавил экран просмотра сезонов и серий для сериалов

2023-04-12 10:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SeasonFragment.kt
> +            if (seasonUiState.isFirstSeason) {
И к тому же почему ты ничего мне не сказал, про второй вариант решения проблемы с чипами?

2023-04-12 10:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SeasonViewModel.kt
> +    private fun getFirstSeason() {
сначала идут public методы

2023-04-12 10:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SerialInfo.kt
> +import java.io.Serializable
А почему не parceble?

2023-04-12 10:04 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/model/FilmDetailUiModel.kt
> +    val isVisibleSeason: Boolean = false,
isSeason?

2023-04-12 15:29 UTC, LuchemeteOtake requested changes

2023-04-12 15:29 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SerialInfo.kt
> +        fun createFilmInfo(id: Int, nameFilm: String): SerialInfo =
createFilmInfo, а возвращает SerialInfo. и чем обычный конструктор не утсроил?

2023-04-12 15:29 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/adapter/SeasonAdapter.kt
> +    fun bind(serialModel: EpisodesModel) {
serialModel, а тип EpisodesModel

2023-04-12 15:29 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SerialModel.kt
> +    val episodeNumber: String,
вроде number, а String

2023-04-12 15:29 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_film_details.xml
а дальше лейаут только больше будет, я правильно понимаю?)

2023-04-12 15:29 UTC, LuchemeteOtake commented on app/src/main/res/values/strings.xml
> +    <string name="season_number_season">%s cезон,</string>
почему не %d?

2023-04-12 15:29 UTC, LuchemeteOtake commented on app/src/main/res/values/strings.xml
> +    <string name="season_number_season">%s cезон,</string>
и почему запятая в конце?

2023-04-13 06:20 UTC, GrigoryKharchenko commented on app/src/main/res/values/strings.xml
> +    <string name="season_number_season">%s cезон,</string>
Не  %d, потому что мне же приходит string, a нe Int
Запятая, потому что  по дизайну так 
![image](https://user-images.githubusercontent.com/96061286/231670859-c04face3-c119-4c78-9af7-c4e9e8b28057.png)

2023-04-13 06:21 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_film_details.xml
нет, больше в него ничего не будет добавляться

2023-04-13 11:19 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/extension/ViewExtension.kt
> +    for (i in 1..countChip) {
Ну а как я к int forEach использую?

2023-04-14 09:35 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/extension/ViewExtension.kt
> +    for (i in 1..countChip) {
а как я могу применить forEach, если он применяется к коллекции, а у меня здесь ее нет

2023-04-14 10:06 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SerialInfo.kt
> +import java.io.Serializable
До этого было parceble, Саша мне сказал, убрать и переделать на Serializable, так как приложение не очень большое и мы не гонимся за скоростью

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/res/values/strings.xml
> +    <string name="season_number_season">%s cезон,</string>
Исправил

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SerialModel.kt
> +    val episodeNumber: String,
Исправил

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/adapter/SeasonAdapter.kt
> +    fun bind(serialModel: EpisodesModel) {
Исправил

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SerialInfo.kt
> +        fun createFilmInfo(id: Int, nameFilm: String): SerialInfo =
Данный класс не используется, поэтому я его удалил

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/model/SerialUiModel.kt
> +    val countEpisodes: SeasonsModel
Исправил

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +                val countSeason = countSeason ?: 0
По дефолту true, так что убрал

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/extension/ViewExtension.kt
> +        isFocusable = true
По дефолту true, так что убрал

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/extension/ViewExtension.kt
> +        isClickable = true
По дефолту true, так что убрал

2023-04-14 10:33 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/model/FilmDetailUiModel.kt
> +    val isVisibleSeason: Boolean = false,
Испраивл

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SeasonViewModel.kt
> +    private fun getFirstSeason() {
исправил

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SeasonFragment.kt
> +            if (seasonUiState.isFirstSeason) {
Исправил

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/season/SeasonFragment.kt
> +                SeasonUiState.Error -> {
исправил

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                        (uiState as? FilmDetailUiState.DetailFilm)?.copy(
испраивл

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/extension/ViewExtension.kt
> +    for (i in 1..countChip) {
испраивл

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/SerialMapper.kt
> +    state.emit(
Убрал

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/SerialMapper.kt
> +        episodeNumber = if (episodeNumber == "0") "1" else episodeNumber,
Убрал

2023-04-14 10:34 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                        (uiState as? FilmDetailUiState.DetailFilm)?.copy(
исправил

2023-04-18 04:17 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/extension/ViewExtension.kt
> +    for (i in 1..countChip) {
Можно было и сообразить открыть доку котлинскую:
(1..countChip).forEach {}
или даже так
repeat((1..5).count()) {}

2023-04-18 08:51 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/extension/ViewExtension.kt
> +    for (i in 1..countChip) {
Переделал

2023-04-18 09:37 UTC, LuchemeteOtake approved these changes

2023-04-19 09:28 UTC, merged