Add search settings screen
GrigoryKharchenko/Cinema pull request #31
Opened 2023-04-10 10:26 UTC by GrigoryKharchenko

Добавил экран с жанрами и фильмами с возможностью поиска

2023-04-18 04:30 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/data/mapper/SearchFiltersMapper.kt
> +    this.countries.map(CountriesFilterResponse::mapToCountryFilter).filter {
Может стоит сначала фильтровать, а потом мапить?

2023-04-18 04:30 UTC, Skripi commented on app/src/main/java/kinopoisk/cinema/data/mapper/SearchFiltersMapper.kt
> +    this.genres.map(GenresFilterResponse::mapToGenreFilter).filter {
аналогично

2023-04-18 09:03 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/SearchFiltersMapper.kt
> +    this.countries.map(CountriesFilterResponse::mapToCountryFilter).filter {
исправил

2023-04-18 09:03 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/SearchFiltersMapper.kt
> +    this.genres.map(GenresFilterResponse::mapToGenreFilter).filter {
исправил

2023-04-18 09:46 UTC, LuchemeteOtake requested changes

2023-04-18 09:46 UTC, LuchemeteOtake commented on app/src/main/res/values/strings.xml
> +    <string name="search_filter_title_genres">Жанр</string>
genres каколе число?

2023-04-18 09:46 UTC, LuchemeteOtake commented on app/src/main/res/layout/item_country_or_genre.xml
> +        app:layout_constraintTop_toBottomOf="@id/tvTitleYear" />
а мы сейчас в каком лейауте?

2023-04-18 09:46 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_search_filter.xml
> +        app:layout_constraintTop_toBottomOf="@id/appBar" />
а мы сейчас в каком лейауте?

2023-04-18 11:18 UTC, GrigoryKharchenko commented on app/src/main/res/layout/item_country_or_genre.xml
> +        app:layout_constraintTop_toBottomOf="@id/tvTitleYear" />
Исправил

2023-04-18 11:18 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_search_filter.xml
> +        app:layout_constraintTop_toBottomOf="@id/appBar" />
Исправил

2023-04-19 07:14 UTC, LuchemeteOtake approved these changes

2023-04-19 09:16 UTC, merged