Add film details screen
GrigoryKharchenko/Cinema pull request #9
Opened 2023-01-22 14:44 UTC by GrigoryKharchenko

Добавил детальный экран фильма

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
Хорошая привычка запятую ставить

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                        actor = detailFilmRepository.getActor(id).filter { filmCrew ->
Обработки всех этих запросов ты решил не делать...

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/gallery/GalleryAdapter.kt
> +            ivGallery.loadCropImage(galleryUiModel.image)
Ради одной строчки писать with(binding)?

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/similar/SimilarAdapter.kt
> +            tvRating.isVisible = false
rating всегда false интересно

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/homepage/HomeFragment.kt
> +        parentFragmentManager.beginTransaction()
Везде используешь другую запись

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/homepage/allcategory/AllCategoryAdapter.kt
> +    private val onFilmClick: (Int) -> Unit
Хорошая пирвычка ставить запятые

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/drawable/black_gradient.xml
> +        android:startColor="@color/start_black_gradient"
это что за названия

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/fragment_film_details.xml
> +                    android:layout_height="400dp"
Это что здесь делает

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/fragment_film_details.xml
> +        android:layout_width="match_parent"
в constraint что должно быть

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/fragment_film_details.xml
> +                    android:layout_width="match_parent"
в constraint что должно быть

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/fragment_film_details.xml
> +                    android:layout_width="@dimen/dp_16"
Почему все каритнки wrap comntnet а это 16dp

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/item_film_crew.xml
> +        android:layout_width="48dp"
почему не в dimean

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/item_gallery.xml
> +        android:layout_width="192dp"
Почему не в dimean

2023-01-23 05:25 UTC, Skripchenko-Nikolai commented on app/src/main/res/values/colors.xml
> +    <color name="start_black_gradient">#1B1B1B</color>
Как я уже гдето писал переименуй

2023-01-23 07:09 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/gallery/GalleryAdapter.kt
> +            ivGallery.loadCropImage(galleryUiModel.image)
в дальнейшем это буде расширяться

2023-01-23 07:12 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/similar/SimilarAdapter.kt
> +            tvRating.isVisible = false
Так как он мне не приходит в запросе, его там никогда и не будет, поэтому чтобы не писать отдельный item, с Никитой это обговаривали

2023-01-23 07:49 UTC, LuchemeteOtake requested changes

2023-01-23 07:49 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmCrewMapper.kt
> +        name = nameRu ?: nameEn,
а в обычном FilmResponse есть ещё и nameOriginal. тут его нет?
name = nameRu ?: nameEn ?: nameOriginal

2023-01-23 07:49 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmsMapper.kt
> +                "\n${countries.joinToString { countries -> countries.country }}, " + "${duration ?: ""} " + (ratingAgeLimits ?: ""),
эт чего за ужас?)
моежт вынести в отдельную функцию или экстеншн?
и почему где-то идет концатенация, а где-то интерполяция?

2023-01-23 07:49 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/network/KinopoiskApi.kt
> +    @Headers("X-API-KEY:${BuildConfig.API_KEY}")
может вынести в интерцептор?

2023-01-23 07:49 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +        binding.rvSimilarFilm.adapter = null
а в initUi 4 адаптера устанавливаются, а тут 3 зануляются...
а ещё with(binding) можно юзать

2023-01-23 07:49 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +        fun newInstance(id: Int) = FilmDetailFragment().apply {
а пометь тогда ещё дефолтный конструктор как депрекейтед

2023-01-23 07:49 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/filmcrew/FilmCrewAdapter.kt
> +class FilmCrewAdapter : ListAdapter<FilmCrewUiModel, FilmCrewViewHolder>(FilmCrewDiffUtil()) {
а чем FilmCrewAdapter от ActorAdapter отличается?

2023-01-23 08:04 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmCrewMapper.kt
> +        name = nameRu ?: nameEn,
Да, это другой запрос и в этом запросе нет nameOriginal, только nameRu и nameEn

2023-01-23 08:23 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_film_details.xml
> +        android:layout_width="match_parent"
Это не constraint, а CoordinatorLayout

2023-01-23 08:31 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +            var isCollapsed = INITIAL_IS_COLLAPSED
Для расширения и сужения TextVIew

2023-01-23 09:29 UTC, Skripchenko-Nikolai commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/gallery/GalleryAdapter.kt
> +            ivGallery.loadCropImage(galleryUiModel.image)
Почитай про паттерн YAGNI и после вернись к этому комментарию

2023-01-24 18:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmCrewMapper.kt
> +fun List<ActorResponse>.mapToFilmCrewsModel(): List<FilmCrewUiModel> =
Исправил

2023-01-24 18:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmCrewMapper.kt
> +        profession = profession
Исправил

2023-01-24 18:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/network/response/DetailFilmResponse.kt
> +    @SerializedName("genres") val genre: List<GenreResponse>,
Исправил

2023-01-24 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/repository/DetailFilmRepositoryImpl.kt
> +    private val kinopoiskApi: KinopoiskApi
Исправил

2023-01-24 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +    private fun getArgs(): Int? = arguments?.getInt(KEY_FILM)
Исправил

2023-01-24 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +                handleUiState(it)
Исправил

2023-01-24 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +                with(binding) {
Исправил

2023-01-24 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailUiState.kt
> +        val detailFilm: FilmDetailUiModel,
Исправил

2023-01-24 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
Исправил

2023-01-24 18:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                        actor = detailFilmRepository.getActor(id).filter { filmCrew ->
Исправил

2023-01-24 18:54 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/gallery/GalleryAdapter.kt
> +            ivGallery.loadCropImage(galleryUiModel.image)
Исправил

2023-01-24 18:54 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/homepage/HomeFragment.kt
> +        parentFragmentManager.beginTransaction()
Исправил

2023-01-24 18:54 UTC, GrigoryKharchenko commented on app/src/main/res/drawable/black_gradient.xml
> +        android:startColor="@color/start_black_gradient"
Исправил

2023-01-24 18:54 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_film_details.xml
> +                    android:layout_height="400dp"
Исправил

2023-01-24 18:54 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_film_details.xml
> +                    android:layout_width="match_parent"
Исправил

2023-01-24 18:55 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_film_details.xml
> +                    android:layout_width="@dimen/dp_16"
Исправил

2023-01-24 18:55 UTC, GrigoryKharchenko commented on app/src/main/res/layout/item_film_crew.xml
> +        android:layout_width="48dp"
Исправил

2023-01-24 18:55 UTC, GrigoryKharchenko commented on app/src/main/res/layout/item_gallery.xml
> +        android:layout_width="192dp"
Исправил

2023-01-24 18:55 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmsMapper.kt
> +                "\n${countries.joinToString { countries -> countries.country }}, " + "${duration ?: ""} " + (ratingAgeLimits ?: ""),
Исправил

2023-01-24 18:55 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/network/KinopoiskApi.kt
> +    @Headers("X-API-KEY:${BuildConfig.API_KEY}")
Исправил

2023-01-24 18:55 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +        binding.rvSimilarFilm.adapter = null
Исправил

2023-01-24 18:56 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailFragment.kt
> +        fun newInstance(id: Int) = FilmDetailFragment().apply {
Исправил

2023-01-24 18:56 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/adpters/filmcrew/FilmCrewAdapter.kt
> +class FilmCrewAdapter : ListAdapter<FilmCrewUiModel, FilmCrewViewHolder>(FilmCrewDiffUtil()) {
Исправил

2023-01-25 03:05 UTC, LuchemeteOtake requested changes

2023-01-25 03:05 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +    private fun getSimilar(id: Int) {
А можно тут все же обойтись без четверной копипасты?

2023-01-25 03:05 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/homepage/HomeFragment.kt
> +            bundle.putInt(FilmDetailFragment.KEY_FILM, filmId)
bundle of что принимает в параметры?

2023-01-25 05:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmDetailMapper.kt
> +    val finalCounty = if (ratingAgeLimits == null && duration == null) countries else "$countries,"
Исправил

2023-01-25 05:52 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmDetailMapper.kt
> +    val duration = if (ratingAgeLimits == null) "${duration ?: ""} " else "$duration мин,"
Исправил

2023-01-25 05:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmDetailMapper.kt
> +    return "$rating $name\n$released $genres\n$finalCounty $duration $ratingAgeLimits"
Исправил

2023-01-25 05:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/homepage/HomeFragment.kt
> +            bundle.putInt(FilmDetailFragment.KEY_FILM, filmId)
Исправил

2023-01-25 05:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/network/response/StuffResponse.kt
> +data class StuffResponse(
Исправил

2023-01-25 05:53 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +    private fun getSimilar(id: Int) {
Пока не придумал другого способа

2023-01-25 06:27 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmDetailMapper.kt
> +    return "$firstPart\n$secondPart\n$thirdPart"
у тебя тут может не быть заголовка вообще? т.е. все поля могут пустыми прийти?

2023-01-25 06:27 UTC, LuchemeteOtake commented on gradle.properties
> +api_key = "25bef63d-45ba-49d7-9844-86e5d6881ffb"
а там ограничение на 500 запросов в день или вообще?
ключ точно надо в пре менять?

2023-01-25 06:43 UTC, GrigoryKharchenko commented on gradle.properties
> +api_key = "25bef63d-45ba-49d7-9844-86e5d6881ffb"
там 500 запрос в день, думаю не надо)

2023-01-25 06:45 UTC, LuchemeteOtake commented on gradle.properties
> +api_key = "25bef63d-45ba-49d7-9844-86e5d6881ffb"
тогда убери из пра)

2023-01-25 06:52 UTC, LuchemeteOtake requested changes

2023-01-25 06:52 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmDetailMapper.kt
> +    val ratingAge = ratingAgeLimits ?: ratingMpaa ?: ""
?: ""

это лишнее

2023-01-25 08:10 UTC, GrigoryKharchenko commented on gradle.properties
> +api_key = "25bef63d-45ba-49d7-9844-86e5d6881ffb"
изменил

2023-01-25 08:21 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/data/mapper/FilmDetailMapper.kt
> +    val ratingAge = ratingAgeLimits ?: ratingMpaa ?: ""
Убрал

2023-01-25 12:10 UTC, LuchemeteOtake requested changes

2023-01-25 12:10 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/domain/InterceptorKey.kt
> +interface InterceptorKey {
а чем стандартный интерцептор из OkHttp не устроил?

2023-01-25 12:54 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/domain/InterceptorKey.kt
> +interface InterceptorKey {
Исправил

2023-01-25 15:47 UTC, LuchemeteOtake requested changes

2023-01-25 15:47 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                _uiStateFlow.emit(
после одной ошибки все остальные успешные результаты игнорятся

2023-01-25 15:47 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                            isVisibleCountActor = actor.isNotEmpty(),
зачем по две переменных на одно и то же значение?

2023-01-25 15:47 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                            isVisibleCountSimilar = false,
а между тем в Success стейте и в Error стейте все эти переменные дублируются. зачем?

2023-01-25 15:58 UTC, LuchemeteOtake requested changes

2023-01-25 15:58 UTC, LuchemeteOtake commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                detailFilmRepository.getStaff(id).filter { actor ->
один и тот же запрос два раза подряд

2023-01-26 06:41 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                _uiStateFlow.emit(
Исправил

2023-01-26 06:41 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                            isVisibleCountActor = actor.isNotEmpty(),
Исправил

2023-01-26 06:41 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                            isVisibleCountSimilar = false,
Исправил

2023-01-26 06:41 UTC, GrigoryKharchenko commented on app/src/main/java/kinopoisk/cinema/presentation/screen/filmdetail/FilmDetailViewModel.kt
> +                detailFilmRepository.getStaff(id).filter { actor ->
Исправил

2023-01-26 09:25 UTC, LuchemeteOtake approved these changes

2023-01-26 09:39 UTC, merged